import { db } from '@/db';
import { foodItems } from '@/db/schema';

async function main() {
    const sampleFoodItems = [
        // Vegetarian Items (20 items)
        {
            itemId: 'v1',
            name: 'Paneer Butter Masala',
            price: 149,
            category: 'veg',
            description: 'Cottage cheese in rich tomato gravy',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T08:00:00').toISOString(),
        },
        {
            itemId: 'v2',
            name: 'Veg Biryani',
            price: 129,
            category: 'veg',
            description: 'Aromatic rice with mixed vegetables',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T08:05:00').toISOString(),
        },
        {
            itemId: 'v3',
            name: 'Dal Tadka',
            price: 99,
            category: 'veg',
            description: 'Yellow lentils tempered with spices',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T08:10:00').toISOString(),
        },
        {
            itemId: 'v4',
            name: 'Chole Bhature',
            price: 119,
            category: 'veg',
            description: 'Spicy chickpeas with fried bread',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T08:15:00').toISOString(),
        },
        {
            itemId: 'v5',
            name: 'Veg Pulao',
            price: 109,
            category: 'veg',
            description: 'Basmati rice with vegetables',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T08:20:00').toISOString(),
        },
        {
            itemId: 'v6',
            name: 'Aloo Paratha',
            price: 89,
            category: 'veg',
            description: 'Potato stuffed flatbread',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T08:25:00').toISOString(),
        },
        {
            itemId: 'v7',
            name: 'Veg Fried Rice',
            price: 99,
            category: 'veg',
            description: 'Stir-fried rice with vegetables',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T08:30:00').toISOString(),
        },
        {
            itemId: 'v8',
            name: 'Palak Paneer',
            price: 139,
            category: 'veg',
            description: 'Cottage cheese in spinach gravy',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T08:35:00').toISOString(),
        },
        {
            itemId: 'v9',
            name: 'Veg Manchurian',
            price: 119,
            category: 'veg',
            description: 'Vegetable balls in tangy sauce',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T08:40:00').toISOString(),
        },
        {
            itemId: 'v10',
            name: 'Mushroom Masala',
            price: 149,
            category: 'veg',
            description: 'Mushrooms in spicy gravy',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T08:45:00').toISOString(),
        },
        {
            itemId: 'v11',
            name: 'Veg Hakka Noodles',
            price: 109,
            category: 'veg',
            description: 'Stir-fried noodles with vegetables',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T08:50:00').toISOString(),
        },
        {
            itemId: 'v12',
            name: 'Veg Spring Rolls',
            price: 99,
            category: 'veg',
            description: 'Crispy rolls with vegetable filling',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T08:55:00').toISOString(),
        },
        {
            itemId: 'v13',
            name: 'Veg Sandwich',
            price: 79,
            category: 'veg',
            description: 'Grilled sandwich with vegetables',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T09:00:00').toISOString(),
        },
        {
            itemId: 'v14',
            name: 'Veg Burger',
            price: 89,
            category: 'veg',
            description: 'Vegetable patty burger',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T09:05:00').toISOString(),
        },
        {
            itemId: 'v15',
            name: 'Masala Dosa',
            price: 99,
            category: 'veg',
            description: 'Crispy crepe with potato filling',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T09:10:00').toISOString(),
        },
        {
            itemId: 'v16',
            name: 'Idli Sambar',
            price: 69,
            category: 'veg',
            description: 'Steamed rice cakes with lentil soup',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T09:15:00').toISOString(),
        },
        {
            itemId: 'v17',
            name: 'Veg Momos',
            price: 89,
            category: 'veg',
            description: 'Steamed vegetable dumplings',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T09:20:00').toISOString(),
        },
        {
            itemId: 'v18',
            name: 'Paneer Tikka',
            price: 159,
            category: 'veg',
            description: 'Grilled cottage cheese skewers',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T09:25:00').toISOString(),
        },
        {
            itemId: 'v19',
            name: 'Veg Pizza',
            price: 179,
            category: 'veg',
            description: 'Italian flatbread with vegetable toppings',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T09:30:00').toISOString(),
        },
        {
            itemId: 'v20',
            name: 'Veg Pasta',
            price: 129,
            category: 'veg',
            description: 'Italian pasta with vegetables',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T09:35:00').toISOString(),
        },
        // Non-Vegetarian Items (20 items)
        {
            itemId: 'nv1',
            name: 'Chicken Biryani',
            price: 179,
            category: 'non-veg',
            description: 'Aromatic rice with tender chicken',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T10:00:00').toISOString(),
        },
        {
            itemId: 'nv2',
            name: 'Butter Chicken',
            price: 199,
            category: 'non-veg',
            description: 'Chicken in creamy tomato gravy',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T10:05:00').toISOString(),
        },
        {
            itemId: 'nv3',
            name: 'Chicken Tikka Masala',
            price: 189,
            category: 'non-veg',
            description: 'Grilled chicken in spicy gravy',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T10:10:00').toISOString(),
        },
        {
            itemId: 'nv4',
            name: 'Egg Curry',
            price: 119,
            category: 'non-veg',
            description: 'Boiled eggs in curry sauce',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T10:15:00').toISOString(),
        },
        {
            itemId: 'nv5',
            name: 'Chicken Fried Rice',
            price: 149,
            category: 'non-veg',
            description: 'Stir-fried rice with chicken',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T10:20:00').toISOString(),
        },
        {
            itemId: 'nv6',
            name: 'Chicken Momos',
            price: 119,
            category: 'non-veg',
            description: 'Steamed chicken dumplings',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T10:25:00').toISOString(),
        },
        {
            itemId: 'nv7',
            name: 'Chicken Burger',
            price: 129,
            category: 'non-veg',
            description: 'Chicken patty burger',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T10:30:00').toISOString(),
        },
        {
            itemId: 'nv8',
            name: 'Chicken Sandwich',
            price: 109,
            category: 'non-veg',
            description: 'Grilled chicken sandwich',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T10:35:00').toISOString(),
        },
        {
            itemId: 'nv9',
            name: 'Chicken Noodles',
            price: 139,
            category: 'non-veg',
            description: 'Stir-fried noodles with chicken',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T10:40:00').toISOString(),
        },
        {
            itemId: 'nv10',
            name: 'Chicken Manchurian',
            price: 159,
            category: 'non-veg',
            description: 'Chicken balls in tangy sauce',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T10:45:00').toISOString(),
        },
        {
            itemId: 'nv11',
            name: 'Fish Fry',
            price: 169,
            category: 'non-veg',
            description: 'Crispy fried fish',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T10:50:00').toISOString(),
        },
        {
            itemId: 'nv12',
            name: 'Prawn Curry',
            price: 199,
            category: 'non-veg',
            description: 'Prawns in spicy gravy',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T10:55:00').toISOString(),
        },
        {
            itemId: 'nv13',
            name: 'Mutton Curry',
            price: 229,
            category: 'non-veg',
            description: 'Tender mutton in rich gravy',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T11:00:00').toISOString(),
        },
        {
            itemId: 'nv14',
            name: 'Chicken Kebab',
            price: 179,
            category: 'non-veg',
            description: 'Grilled chicken skewers',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T11:05:00').toISOString(),
        },
        {
            itemId: 'nv15',
            name: 'Chicken Wings',
            price: 149,
            category: 'non-veg',
            description: 'Spicy fried chicken wings',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T11:10:00').toISOString(),
        },
        {
            itemId: 'nv16',
            name: 'Chicken Pizza',
            price: 209,
            category: 'non-veg',
            description: 'Italian flatbread with chicken toppings',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T11:15:00').toISOString(),
        },
        {
            itemId: 'nv17',
            name: 'Chicken Pasta',
            price: 169,
            category: 'non-veg',
            description: 'Italian pasta with chicken',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T11:20:00').toISOString(),
        },
        {
            itemId: 'nv18',
            name: 'Egg Biryani',
            price: 139,
            category: 'non-veg',
            description: 'Aromatic rice with boiled eggs',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T11:25:00').toISOString(),
        },
        {
            itemId: 'nv19',
            name: 'Chicken Roll',
            price: 99,
            category: 'non-veg',
            description: 'Chicken wrapped in flatbread',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T11:30:00').toISOString(),
        },
        {
            itemId: 'nv20',
            name: 'Fish Curry',
            price: 189,
            category: 'non-veg',
            description: 'Fish in tangy curry sauce',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify([]),
            offer: null,
            createdAt: new Date('2024-01-10T11:35:00').toISOString(),
        },
        // Combo Offers (8 items)
        {
            itemId: 'c1',
            name: 'Veg Combo 1',
            price: 199,
            category: 'combo',
            description: 'Complete veg meal',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify(['Veg Biryani', 'Raita', 'Salad']),
            offer: 'Save ₹30',
            createdAt: new Date('2024-01-10T12:00:00').toISOString(),
        },
        {
            itemId: 'c2',
            name: 'Veg Combo 2',
            price: 249,
            category: 'combo',
            description: 'Full veg thali',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify(['Paneer Butter Masala', '3 Roti', 'Rice', 'Dal']),
            offer: 'Save ₹40',
            createdAt: new Date('2024-01-10T12:05:00').toISOString(),
        },
        {
            itemId: 'c3',
            name: 'Chicken Combo 1',
            price: 249,
            category: 'combo',
            description: 'Complete chicken meal',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify(['Chicken Biryani', 'Raita', 'Salad']),
            offer: 'Save ₹40',
            createdAt: new Date('2024-01-10T12:10:00').toISOString(),
        },
        {
            itemId: 'c4',
            name: 'Chicken Combo 2',
            price: 299,
            category: 'combo',
            description: 'Full chicken thali',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify(['Butter Chicken', '3 Roti', 'Rice', 'Dal']),
            offer: 'Save ₹50',
            createdAt: new Date('2024-01-10T12:15:00').toISOString(),
        },
        {
            itemId: 'c5',
            name: 'Breakfast Combo',
            price: 149,
            category: 'combo',
            description: 'Filling breakfast',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify(['2 Aloo Paratha', 'Curd', 'Pickle']),
            offer: 'Save ₹20',
            createdAt: new Date('2024-01-10T12:20:00').toISOString(),
        },
        {
            itemId: 'c6',
            name: 'Chinese Combo',
            price: 179,
            category: 'combo',
            description: 'Chinese platter',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify(['Veg Fried Rice', 'Veg Manchurian', 'Spring Roll']),
            offer: 'Save ₹30',
            createdAt: new Date('2024-01-10T12:25:00').toISOString(),
        },
        {
            itemId: 'c7',
            name: 'South Indian Combo',
            price: 129,
            category: 'combo',
            description: 'South Indian breakfast',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify(['2 Idli', '1 Dosa', 'Sambar', 'Chutney']),
            offer: 'Save ₹20',
            createdAt: new Date('2024-01-10T12:30:00').toISOString(),
        },
        {
            itemId: 'c8',
            name: 'Fast Food Combo',
            price: 169,
            category: 'combo',
            description: 'Quick meal combo',
            imageUrl: '',
            paymentModes: JSON.stringify(['cash', 'upi', 'card']),
            items: JSON.stringify(['Veg Burger', 'French Fries', 'Cold Drink']),
            offer: 'Save ₹30',
            createdAt: new Date('2024-01-10T12:35:00').toISOString(),
        },
    ];

    await db.insert(foodItems).values(sampleFoodItems);
    
    console.log('✅ Food items seeder completed successfully - 48 items added');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});